name: money_exchange
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_multi_formatter: ^2.2.1
  google_fonts: ^3.0.1
  icons_launcher: ^2.0.6
  intl: ^0.17.0
  mvc_pattern: ^8.12.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/
icons_launcher:
  image_path: "assets/img/logo.png"
  platforms:
    android:
      enable: true
      image_path: "assets/img/logo.png"
      adaptive_foreground_image: "assets/img/logo.png"
      adaptive_background_color: "#613EEA"
    ios:
      enable: true
      image_path: "assets/img/logo.png"
